# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /opt/recipe, last modified Thu Feb 15 02:57:38 2018
# ------------------------------------------------

package:
    name: trinity
    version: 2.5.1
source:
    fn: Trinity-v2.5.1.tar.gz
    patches:
        - makefile.clean.patch
        - trinity-plugins.makefile.clean.patch
    sha256: bf14f96981bb028d7960dec895a1bcbda1fadbbe562a913b188559fd74b90457
    url: https://github.com/trinityrnaseq/trinityrnaseq/archive/Trinity-v2.5.1.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '1'
    string: '1'
requirements:
    build:
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - mpfr 3.1.5 0
        - xz 5.2.3 0
        - cloog 0.18.0 0
        - isl 0.12.2 0
        - openssl 1.0.2n 0
        - perl-threaded 5.22.0 pl5.22.0_12
        - mpc 1.0.3 4
        - samtools 1.7 1
        - bzip2 1.0.6 1
        - zlib 1.2.11 0
        - libgcc-ng 7.2.0 h7cc24e2_2
        - gmp 6.1.2 0
        - perl-app-cpanminus 1.7039 pl5.22.0_3
        - fastool 0.1.4 2
        - libssh2 1.8.0 2
        - gcc 4.8.5 7
        - libgcc 7.2.0 h69d50b8_2
        - krb5 1.14.2 0
        - slclust 02022010 2
        - ca-certificates 2018.1.18 0
        - openjdk 8.0.144 zulu8.23.0.3_1
        - jellyfish 2.2.6 0
        - perl 5.22.0.1 0
        - perl-module-build 0.4224 pl5.22.0_0
        - collectl 4.0.4 2
        - curl 7.55.1 0
        - parafly r2013_01_21 1
        - trimmomatic 0.36 5
    run:
        - bowtie
        - bowtie2 >=2.3.0
        - collectl
        - fastool
        - jellyfish >=2.2.6
        - libgcc
        - openjdk
        - parafly
        - perl-app-cpanminus
        - perl-module-build
        - samtools >=1.3
        - slclust
        - trimmomatic >=0.36
        - zlib 1.2.11*
test:
    commands:
        - Trinity --cite &> /dev/null
        - align_and_estimate_abundance.pl --help &> /dev/null || [[ "$?" == 255 ]]
        - abundance_estimates_to_matrix.pl --help &> /dev/null || [[ "$?" == 255 ]]
        - run_DE_analysis.pl -h &> /dev/null || [[ "$?" == 255 ]]
        - analyze_diff_expr.pl -h &> /dev/null || [[ "$?" == 255 ]]
        - PtR --help &> /dev/null || [[ "$?" == 255 ]]
        - TrinityStats.pl 2>&1 | grep "usage:" &> /dev/null
        - define_clusters_by_cutting_tree.pl 2>&1 | grep "define K clusters via k-means
            algorithm" &> /dev/null
about:
    home: https://github.com/trinityrnaseq/trinityrnaseq/
    license: BSD-3-Clause
    summary: Trinity RNA-Seq de novo transcriptome assembly
extra:
    final: true
